### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by sgmihai** [louisbui63/game_handler#1]
Hey. Very nice project, I was looking for existing such projects to look at code design/structure. I am learning rust to make something similar.
I couldn't build your project. I tried `git submodule update --init --recursive` and `git submodule update --remote` but nothing happened. So I cloned them manually from github in the project folder, then did cargo run,
```error: failed to select a version for `js-sys`.
    ... required by package `wgpu v0.17.0`
    ... which satisfies dependency `wgpu = "^0.17"` of package `glyphon v0.3.0 (https://github.com/grovesNL/glyphon.git?rev=20f0f8fa80e0d0df4c63634ce9176fa489546ca9#20f0f8fa)`
    ... which satisfies git dependency `glyphon` of package `iced_wgpu v0.12.0 (/tmp/rgl/game_handler/iced/wgpu)`
    ... which satisfies path dependency `iced_wgpu` of package `iced_renderer v0.12.0 (/tmp/rgl/game_handler/iced/renderer)`
    ... which satisfies path dependency `iced_renderer` of package `iced v0.12.0 (/tmp/rgl/game_handler/iced)`
    ... which satisfies path dependency `iced` of package `game_handler v0.1.0 (/tmp/rgl/game_handler)`
versions that meet the requirements `^0.3.64` are: 0.3.64

all possible versions conflict with previously selected packages.

  previously selected package `js-sys v0.3.61`
    ... which satisfies dependency `js-sys = "^0.3.61"` (locked to 0.3.61) of package `wasm-bindgen-futures v0.4.34`
    ... which satisfies dependency `wasm-bindgen-futures = "^0.4"` (locked to 0.4.34) of package `iced_futures v0.12.0 (/tmp/rgl/game_handler/iced/futures)`
    ... which satisfies path dependency `iced_futures` of package `iced v0.12.0 (/tmp/rgl/game_handler/iced)`
    ... which satisfies path dependency `iced` of package `game_handler v0.1.0 (/tmp/rgl/game_handler)`

failed to select a version for `js-sys` which could resolve this conflict
```

Would appreciate help with this, if project is in testable state.

**Comment by louisbui63** [comment]
Hi, I believe this is because I used modified versions of iced and a few other crates, that I never found out how to properly upload to Github. This should be fixed in the latest commit.

**Comment by louisbui63** [comment]
To clarify, you will still be unable to get the submodules, but the compilation process doesn't rely on them anymore.

**Comment by sgmihai** [comment]
Same error after the last commit, doesn't seem related to the problem.

**Comment by louisbui63** [comment]
I forgot to push yesterday, so it might work now.

**Comment by sgmihai** [comment]
Great, it compiles and runs now.
Would be nice if some parts of the code could be extracted as a library, like modules to run various emulators, passing along rom/disc path, emulator/game specific options (if different from the ones initialized as default), and so on. Maybe also modules to query various databases for a specific platform, to show game metadata for an added title.
Do you plan to continue work on this project in the future or is it a dead experiment ?
I'm thinking of a proper database/ desktopapp-like ui, with a retroarch kind of backend, multi-platform. Wine config stuff would be nice as well, but not a priority for me.
Similar projects to what I have in mind(but not cross platform):
https://github.com/tonywoode/quickPlay
metropolis: https://metropolis-launcher.net/img/screenshots/06_Main-Context_Menu.png
and of course, https://playnite.link/

**Comment by sgmihai** [comment]
I just found this lib now: https://github.com/krypt0nn/wincompatlib Maybe it's worth checking out.

**Comment by louisbui63** [comment]
While there are still a few features that I want to try to implement (sorting, a search bar, and controller support), this project is mostly a dead experiment, as I have been focusing more on work lately.
I also believe that making modules for each runner/emulator isn't that useful, as the process creation is heavily dependent on tokio because of specific quirks in iced. This is also what makes the use of crates such as wincompatlib very difficult in this context.
